#!/bin/sh
set -eu

. /functions

for upstream_name in $(get_list_of_upstreams); do
    # Retrieve upstream variables
    # Export those needed for envsubst templating
    export UPSTREAM_URL="$(read_upstream_parameter $upstream_name url)"
    export UPSTREAM_SUBDOMAIN="$(read_upstream_parameter $upstream_name subdomain)"
    export UPSTREAM_INCLUDE="$(read_upstream_parameter $upstream_name include)"
    upstream_config="/etc/nginx/conf.d/${upstream_name}.conf"
    # Check connectivity to the upstream
    if curl "$UPSTREAM_URL"; then
        # If the config for a responding upstream does not exist, create it
        if [ ! -f "$upstream_config" ]; then
            export DOLLAR_SIGN='$'
            cat "/src/upstream.conf.tpl" | envsubst > "$upstream_config"
            touch /signaling/reload-nginx
        fi
    else
        # If the config file for an unresponsive upstream exists, delete it
        [ -f "$upstream_config" ] \
        && rm "$upstream_config" \
        && touch /signaling/reload-nginx
    fi
done

if [ -f /signaling/reload-nginx ]; then
    nginx -s reload
    rm /signaling/reload-nginx
fi
