common: |
  limit_req_zone $binary_remote_addr zone=mylimit:10m rate=1r/s;
upstreams:
  site1:
    url: http://site1
    subdomain: site1
  site2:
    url: http://site2
    subdomain: site2
    include: |
      limit_req zone=mylimit;